---
layout: post
title: Overriding Default Werkzeug Exceptions in Flask
date: 2015-12-07 17:47:17.000000000 +03:00
type: post
parent_id: '0'
published: true
password: ''
status: publish
categories: []
tags:
- code
- development
- exceptions
- Flask
- Flask-RESTful
- how-to
- python
- software
- werkzeug
meta:
  _wpcom_is_markdown: '1'
  _edit_last: '10080708'
  geo_public: '0'
  _rest_api_published: '1'
  _rest_api_client_id: '11'
  _publicize_job_id: '17565767605'
author:
  login: wswld
  email: seva17@gmail.com
  display_name: wswld
  first_name: ''
  last_name: ''
---
<p>Let's play a game here. What HTTP code is this exception:</p>
<p>[code lang="js"]<br />
{<br />
&quot;message&quot;: &quot;The browser (or proxy) sent a request that this server could not understand.&quot;<br />
}<br />
[/code]</p>
<p>No no, you don't look at the code in response! That's cheating! This is actually a default Werkzeug description for <code>400</code> code. No shit. I thought something is bad with my headers or encryption, but I would never guess simple <code>Bad request</code> from this message. You could use a custom exception of course, the problem is, that the very useful <code>abort(400)</code> object (it's an <code>Aborter</code> in disguise) would stick with the default exception anyway.</p>
<p>Let's fix it, shall we?</p>
<p>There may be several possible ways of fixing that, but what I'm gonna do is just update <code>abort.mapping</code>. Create a separate module for your custom HTTP exceptions <code>custom_http_exceptions.py</code> and put a couple of overridden exceptions there (don't forget to import <code>abort</code> we'll be needing that in a moment):</p>
<p>[code lang="python"]<br />
from flask import abort<br />
from werkzeug.exceptions import HTTPException</p>
<p>class BadRequest(HTTPException):<br />
    code = 400<br />
    description = &#039;Bad request.&#039;</p>
<p>class NotFound(HTTPException):<br />
    code = 404<br />
    description = &#039;Resource not found.&#039;<br />
[/code]</p>
<p>These are perfectly functional, but we still need to add it to the default <code>abort</code> mapping:</p>
<p>[code lang="python"]<br />
abort.mapping.update({<br />
    400: BadRequest,<br />
    404: NotFound<br />
})<br />
[/code]</p>
<p>Note that I import <code>abort</code> object from <code>flask</code>, not <code>flask-restful</code>, only the former is an <code>Aborter</code> object with mapping and other bells and whistles, the latter is just a function.</p>
<p>Now just import this module with <code>*</code> to your <em>app</em> Flask module (where you declare and run your Flask app) or someplace it would have a similar effect on runtime.</p>
<p>Note that you also should have the following line in your config because of <a href="http://stackoverflow.com/questions/34066290/custom-abort-mapping-exceptions-in-flask">this issue</a>:</p>
<p>[code lang="python"]<br />
ERROR_404_HELP = False<br />
[/code]</p>
<p>I'm not sure why this awkward and undocumented constant isn't <code>False</code> by default. I opened <a href="https://github.com/flask-restful/flask-restful/issues/545">an issue</a> on GitHub, but no one seems to care.</p>
